### ISSUE TITLE
Support SameSite cookie property

### ISSUE THREAD

**Issue by esabol** [mschout/apache-authcookie#10]
All the major browsers have been updated to support this cookie property.

References:
https://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/
https://www.netsparker.com/blog/web-security/same-site-cookie-attribute-prevent-cross-site-request-forgery/
https://www.owasp.org/index.php/SameSite
https://caniuse.com/#search=samesite

Something like the following is working well for me:

```diff
--- AuthCookie.pm~      2013-04-12 13:22:56.866608000 -0400
+++ AuthCookie.pm       2019-03-26 19:13:37.809237000 -0400
@@ -527,6 +527,15 @@
         $string .= '; HttpOnly';
     }
 
+    # SameSite is an anti-CSRF cookie extension.  See
+    # https://www.owasp.org/index.php/SameSite
+    if (my $samesite = $r->dir_config("${auth_name}SameSite")) {
+       if ($samesite =~ /\b(strict|lax)\b/i) {
+           $samesite = lc($1);
+           $string .= "; SameSite=$samesite";
+       }
+    }
+
     return $string;
 }

```

Maybe `SameSite=lax` should be the default even?

**Comment by mschout** [comment]
Seems like a good idea.  Probably shouldn't enable by default given how long in tooth AuthCookie is, but is definitely worth adding.  I'll try to get to this soon.

**Comment by esabol** [comment]
Do you want me to submit a PR? It’s not many lines. I figured it would be more efficient if you just made the change, but there’s updating the pod and adding a test, too.

**Comment by mschout** [comment]
Sure, go ahead.

**Comment by esabol** [comment]
PR #11 submitted.

**Comment by esabol** [comment]
Thanks! Shall I close the issue now or wait until the next version is released to CPAN?

**Comment by esabol** [comment]
Any plans to release this to CPAN? Thanks!

**Comment by mschout** [comment]
Oh wow.  I thought I had done that already.  This completely slipped my mind.  I'll do it tonight.  Apologies.

**Comment by esabol** [comment]
Ping!

**Comment by mschout** [comment]
I just pushed it to CPAN.  Should hit the mirrors over the next few hours.

**Comment by esabol** [comment]
Thank you!
