### ISSUE TITLE
Enforce local destination?

### ISSUE THREAD

**Issue by esabol** [mschout/apache-authcookie#12]
A security audit of our system (based on Apache::AuthCookie) complained that we weren't enforcing a local destination. Since the destination is a parameter to the login form, a malicious man-in-the-middle entity could potentially intercept the login and change the destination to a different site, perhaps fooling the user into thinking they were still on our site, or so the thinking goes by the auditors.

Anyway, I have relatively small patch that implements this enforcement of a local destination:
```diff
--- /www/htdocs/cgi-bin/lib/modperl/Apache2/AuthCookie/Base.pm_v3.28_orig      2019-11-19 10:36:52.000000000 -0500
+++ /www/htdocs/cgi-bin/lib/modperl/Apache2/AuthCookie/Base.pm_new      2020-01-08 15:44:00.377183000 -0500
@@ -2 +2 @@
-$Apache2::AuthCookie::Base::VERSION = '3.28';
+$Apache2::AuthCookie::Base::VERSION = '3.28_01';
@@ -276,0 +277,7 @@
+    # Enforce that the destination must be local.
+    my $destination = $params->param('destination');
+    if ($destination !~ /\A\// || $destination =~ /[<>:\"\']/) {
+        $r->server->log_error("invalid destination $destination detected for uri ",$r->uri);
+        $destination = $r->dir_config("${auth_name}DefaultDestination") || '/';
+        $r->server->log_error("destination changed to default $destination");
+    }
@@ -294 +301 @@
-        $r->uri($self->untaint_destination($params->param('destination')));
+        $r->uri($self->untaint_destination($destination));
@@ -308 +315 @@
-        $r->server->log_error("redirect to ", $params->param('destination'));
+        $r->server->log_error("redirect to ", $destination);
@@ -312 +319 @@
-        "Location" => $self->untaint_destination($params->param('destination')));
+        "Location" => $self->untaint_destination($destination));
```
Would you be interested in incorporating this change? I could submit a PR, but, if you don't think this change is warranted, I'll just close this issue.

**Comment by mschout** [comment]
Its not a bad idea, but we need to make it configurable, and not the default.

IE you would have to "opt in" by turning it on in the config.   So we would have to introduce something like `PerlSetVar MyAuthCookieEnforceLocalDestination On` or something. The reason is that AuthCookie dates back to the previous millenia and we cannot risk breaking legacy apps that have AuthCookie deployed.

**Comment by esabol** [comment]
> Its not a bad idea, but we need to make it configurable, and not the default.

Sure, that makes sense. Is the following sufficient for doing that or do I also need to make the `dir_config` return value is not "Off"?
```Perl
    if ($r->dir_config("${auth_name}EnforceLocalDestination")) {
       ...
    }
```

**Comment by esabol** [comment]
Dumb question: How do you generate the Makefile.PL when you make a release? I'm trying to add some test cases for this new functionality and want to test....

**Comment by mschout** [comment]
Seems in this module its generally `1` for on and `0` for off, so I think what you have is fine.

As for the makefile, I'm using Dist::Zilla, so you can do something like this if you don't have `Dist::Zilla` installed yet:

```
cpanm Dist::Zilla
dzil authordeps --missing | cpanm
```

and then you can create a dist with

```
dzil build
```

Or just run the tests with `dzil test`

**Comment by esabol** [comment]
Wow, that's a lot of dependencies for `Dist::Zilla`!

`dzil build` left me with a `Makefile.PL` that caused a warning (I think):
```
Argument "6.63_03" isn't numeric in subroutine entry at Makefile.PL line 65.
```
Makefile.PL line 65 says:
```Perl
unless ( eval { ExtUtils::MakeMaker->VERSION('6.63_03') } ) {
```
Anyway, I presume I have an odd version of some module somewhere. I worked around it easily enough.

**Comment by mschout** [comment]
Release in v3.29
