### ISSUE TITLE
$self missing in sub authenticate()

### ISSUE THREAD

**Issue by landau351** [mschout/apache-authcookie#14]
At this point;
[https://metacpan.org/source/MSCHOUT/Apache-AuthCookie-3.28/lib/Apache2/AuthCookie/Base.pm#L23](https://metacpan.org/source/MSCHOUT/Apache-AuthCookie-3.28/lib/Apache2/AuthCookie/Base.pm#L23)

 `   my ($auth_type, $r) = @_;`
should be;
`    my ($self,$auth_type, $r) = @_;`

**Comment by esabol** [comment]
No, it’s correct as it is. Apache doesn’t call `authenticate()` as either an object method or a class method.
