### ISSUE TITLE
libapache2-authcookie-perl: autopkgtest regression with Perl 5.40: Attempt to call undefined import method with arguments

### ISSUE THREAD

**Issue by real-dam** [mschout/apache-authcookie#17]
We have the following bug reported to the Debian package of
Apache-AuthCookie, c.f. https://bugs.debian.org/1078092

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: libapache2-authcookie-perl
Version: 3.31-2
Severity: important
User: debian-perl@lists.debian.org
Usertags: perl-5.40-transition

This package warns on usage with Perl 5.40 (currently in experimental),
making its autopkgtest checks fail.

  https://ci.debian.net/packages/liba/libapache2-authcookie-perl/unstable/amd64/50041830/

  $ perl -we 'use Apache2::AuthCookie'
  Attempt to call undefined import method with arguments ("1.99022") via package "mod_perl2" (Perhaps you forgot to load the package?) at /usr/share/perl5/Apache2/AuthCookie/Base.pm line 6.

Information on the new warning can be found at

  https://metacpan.org/dist/perl/view/pod/perldelta.pod#Calling-the-import-method-of-an-unknown-package-produces-a-warning

-- 
Niko Tyni   ntyni@debian.org


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Changing the version requirement in Apache2/AuthCookie/Base.pm to

 use mod_perl2 1.99022;

(without the quotes around the version) avoids the warning with perl 5.40.

Thanks for considering,
  Damyan Ivanov,
  Debian Perl Group

**Comment by esabol** [comment]
There's an open PR in Perl that would fix this: https://github.com/Perl/perl5/pull/21279

But it's been open for almost a year, and it doesn't seem likely that it will be merged anytime soon.

And, apparently, the version number should have never been a string in the first place.

**Comment by mschout** [comment]
Merged.

**Comment by esabol** [comment]
It's a pretty minor change, but, for compatibility with Perl 5.40+, I think a new CPAN release of this module would be useful.

**Comment by mschout** [comment]
@esabol new version was released on Saturday. https://metacpan.org/release/MSCHOUT/Apache-AuthCookie-3.32/source/Changes

**Comment by esabol** [comment]
Wonderful! Thank you, @mschout !
