### ISSUE TITLE
Tests fail - no apache.conf ?

### ISSUE THREAD

**Issue by castaway** [mschout/apache-authcookie#6]
Hi, just tried to upgrade from 3.24 to 3.26, and I have issues with running tests: 

[warning] setting ulimit to allow core files
ulimit -c unlimited; /usr/bin/perl /home/jessr/.cpanm/work/1476437874.32308/Apache-AuthCookie-3.26/t/TEST -bugreport -verbose=0 't/author-pod-syntax.t' 't/real.t' 't/signature.t' 't/util.t'
apache2: Could not open configuration file /home/jessr/.cpanm/work/1476437874.32308/Apache-AuthCookie-3.26/t/apache2.conf: No such file or directory
/usr/sbin/apache2  -d /home/jessr/.cpanm/work/1476437874.32308/Apache-AuthCookie-3.26/t -f /home/jessr/.cpanm/work/1476437874.32308/Apache-AuthCookie-3.26/t/conf/httpd.conf -D APACHE2 -D APACHE2_4 -D PERL_USEITHREADS
using Apache/2.4.18 

waiting 60 seconds for server to start: .AH00534: apache2: Configuration error: No MPM loaded.
[  error] 
server has died with status 255 (t/logs/error_log wasn't created, start the server in the debug mode)
Terminated
Makefile:907: recipe for target 'run_tests' failed

full cpanm log file available if required.. any ideas? It does (once forced) fix the issue we were having with AH00027 (user setting in subrequests), so would love to install it.

**Comment by mschout** [comment]
Looks like Apache::Test misconfigured your t/conf/httpd.conf

Without seeing the t/conf/* files that Apache::Test generated I'm guessing your OS httpd.conf doesn't load a mod_mpm_* module directly and Apache::Test didn't pull that in.

This is Apache::Test's fault, not AuthCookie.

If you could ensure that you have the latest version of Apache::Test (1.40 apparently), and try again with v1.40 to see if that fixes it.  If not, you should file a bug report with Apache::Test.
