### ISSUE TITLE
Can't locate object method "requires" via package "Apache2::RequestRec"

### ISSUE THREAD

**Issue by paulraines68** [mschout/apache-authcookie#7]
I am trying to use Apache-AuthCookie on a CentOS7 box with mod_perl-2.0.10 but get the error:

Can't locate object method "requires" via package "Apache2::RequestRec" at /usr/share/perl5/vendor_perl/Apache2/AuthCookie/Base.pm line 167.

**Comment by mschout** [comment]
What apache version are you running?

This sounds an awful lot like you are running under Apache 2.4, and you called authorize(), or, you have misconfigured authcookie to call authorize (via PerlAuthzHandler), which is illegal under Apache 2.4. 

Things are *VERY* difference under Apache 2.4.  Apache completely rewrote how authentication works under Apache 2.4. 

Assuming you are running under apache 2.4, you will need to port your AuthCookie subclass over to work under the new Apache authentication and authorization API.

At a minimum, you need to get rid of all PerlAuthzHandler configuration entries.  If you are merely doing "require valid-user", or "require user ..." you dont need to create a custom Authz provider.  If you are doing anythying more complicated, you will need to write a PerlAuthzProvider handler instead under Apache 2.4.

Assuming you are running under apache 2.4, you will need to port your AuthCookie subclass over to work under the new Apache authentication and authorization API.

the README.apache-2.4.pod file, included in the dist, will get you started with the rest of what you need to do.  I will note that the README says you need to inherit from Apache2_4::AuthCookie, but technically this is not true.

Depending on what your AuthCookie subclass does, porting to Apache 2.4 might be not that difficult, or, it could be a massive headache.  But, if you want to run under Apache 2.4 you have no choice but to port it.

**Comment by paulraines68** [comment]
Thanks.  Removing "PerlAuthzHandler NMRAuth::AuthCookieHandler->authorize" did the trick.
