### ISSUE TITLE
Problems in 3.25 and later

### ISSUE THREAD

**Issue by jira** [mschout/apache-authcookie#9]
Hi,

in 3.25 and later my setup silently stopped working. Instead of being redirected to login page I get 403 error.

I'm on apache 2.2, and mod_perl 2.0.10. My config below.

```
PerlSetVar 'Prosyn IntranetPath' /private
PerlSetVar 'Prosyn IntranetLoginScript' /private/bin/login.pl
PerlSetVar 'Prosyn IntranetCookieName' ps_intranet_devel
PerlSetVar 'Prosyn IntranetExpires' +1y

<LocationMatch ^/private.*>
  AuthType Prosyn::AuthCookieHandler
  AuthName "Prosyn Intranet"
  PerlAuthenHandler Prosyn::AuthCookieHandler->authenticate
  PerlAuthzHandler Prosyn::AuthCookieHandler->authorize
  require valid-user
</LocationMatch>


<Directory "/opt/project-syndicate/var/www/intranet">

AuthType ProjectSyndicate::AuthCookieHandler
AuthName "Prosyn Intranet"
PerlAuthenHandler Prosyn::AuthCookieHandler->authenticate
PerlAuthzHandler Prosyn::AuthCookieHandler->authorize
require valid-user

order deny,allow
allow from all
SSLRequireSSL
Options +ExecCGI +FollowSymLinks

DirectoryIndex bin/index.pl

AllowOverride All
</Directory>
```

**Comment by mschout** [comment]
For sure one problem is that your LoginScript is in /private/bin/login.pl, but you have:
  
   <LocationMatch ^/private.*>
      require valid-user
    </LocationMatch>

So you would have to be logged in to access login.pl, but given that login.pl's entire purpose is to log in an unauthenticated user, I don't see how this ever could have worked.

**Comment by jira** [comment]
Dunno, this worked till 3.24.
Not sure if there was something else involved, but just downgrading made it work.
Anyway, moving the login script makes it work in the latest version too.

Thanks.

**Comment by mschout** [comment]
Yeah, the login script has always supposed to have been outside of the protected area.  Closing this as a result.
